services:
  postgresql:
    image: postgres:15
    container_name: dml_data_platform_postgres_dev
    env_file:
      - ./env/.env.dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dml_data_platform_dev_nw
  
  minio:
    image: minio/minio:latest
    container_name: dml_data_platform_minio_dev
    env_file:
      - ./env/.env.dev
    networks:
      - dml_data_platform_dev_nw
    volumes:
      - ./storage/minio:/data
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    command: ["server", "/data", "--console-address", ":9001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  dagster_daemon:
    build:
      context: .
      dockerfile: docker/dev/dagster/Dockerfile
    container_name: dml_data_platform_dagster_daemon_dev
    env_file:
      - ./env/.env.dev
    command: ["dagster-daemon", "run"]
    volumes:
      - ./dml-orchestrator/src:/opt/app/src
      - ./dml-dbt/dml_dbt_platform:/opt/dbt/project
    depends_on:
      - postgresql
      - minio
    networks:
      - dml_data_platform_dev_nw
    restart: on-failure
  
  dagster_webserver:
    build:
      context: .
      dockerfile: docker/dev/dagster/Dockerfile
    container_name: dml_data_platform_dagster_webserver_dev
    env_file:
      - ./env/.env.dev
    command: [ "dagster-webserver", "-h", "0.0.0.0", "-p", "3000" ]
    volumes:
      - ./dml-orchestrator/src:/opt/app/src
      - ./dml-dbt/dml_dbt_platform:/opt/dbt/project
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
      - minio
    networks:
      - dml_data_platform_dev_nw
    restart: on-failure

volumes:
  postgres_data_dev:

networks:
  dml_data_platform_dev_nw:
    driver: bridge